version: 1
builds:
  - src: package.json
    use: '@render/angular'
    config:
      buildCommand: npm run build
      publishPath: dist/silianos-ng/browser
routes:
  - src: /assets/(.*)
    dest: /assets/$1
  - src: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$)
    dest: /$1
  - src: /.*
    dest: /index.html
